---
- name: Cisco iOS devices
  hosts: Test
  gather_facts: no

  tasks:
    - name: Create Directory for each switch
      file:
        path: /home/netAdmin/cdp_ssh_output/{{ inventory_hostname }}
        state: directory
        mode: '0777'

    - name: Show commands
      #ignore_errors: yes
      ios_command:
        commands:
          - show cdp neighbors
          - show int description | exc DOT
          - show ip ssh
          - show run | sec hostname
          - show run | sec ip domain-name
          - show run | sec name-server

      register: cisco_config

    - name: Show cdp neighbors
      copy:
        content: "{{ cisco_config.stdout[0] }}"
        dest: "/home/netAdmin/cdp_ssh_output/{{ inventory_hostname }}/show_cdp_neighbors.txt"

    - name: show int description
      copy:
        content: "{{ cisco_config.stdout[1] }}"
        dest: "/home/netAdmin/cdp_ssh_output/{{ inventory_hostname }}/show_int description.txt"

    - name: Show ip ssh
      copy:
        content: "{{ cisco_config.stdout[2] }}"
        dest: "/home/netAdmin/cdp_ssh_output/{{ inventory_hostname }}/show_ip-ssh.txt"
        
    - name: Show hostname
      copy:
        content: "{{ cisco_config.stdout[3] }}"
        dest: "/home/netAdmin/cdp_ssh_output/{{ inventory_hostname }}/show_hostname.txt"
        
    - name: show ip domain-name
      copy:
        content: "{{ cisco_config.stdout[4] }}"
        dest: "/home/netAdmin/cdp_ssh_output/{{ inventory_hostname }}/show_domain-name.txt"
        
    - name: Show name-server
      copy:
        content: "{{ cisco_config.stdout[5] }}"
        dest: "/home/netAdmin/cdp_ssh_output/{{ inventory_hostname }}/show_name-server.txt"
...
